name: gopherescape
description: "Gopher exploring search algorithms to escape from the maze"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  skeletonizer: ^1.4.3
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.0
  dartz: ^0.10.1
  rename: ^3.0.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Icons
    - assets/icons/
    # Images
    - assets/images/
    # Fonts
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/inter/Inter-Black.otf
          weight: 900
